{
    parserClass='io.j99.idea.vue.parser.VueParser'
    implements='io.j99.idea.vue.psi.VueCompositeElement'
    extends='io.j99.idea.vue.psi.impl.VueCompositeElementImpl'
    extends("body_code")='io.j99.idea.vue.psi.impl.VueCompositeHostElementImpl'

    elementTypeHolderClass='io.j99.idea.vue.VueTypes'
    elementTypeClass='io.j99.idea.vue.psi.VueCompositeElementType'
    tokenTypeClass='io.j99.idea.vue.psi.VueTokenType'
    psiClassPrefix='Vue'
    psiImplClassSuffix='Impl'
    psiPackage='io.j99.idea.vue.psi'
    psiImplPackage='io.j99.idea.vue.psi.impl'
}
private root::=tags
tags    ::='<' tagName ' lang=' lang '>' body_code '</' tagName '>'
tagName ::=
body_code ::=