{
    parserClass='io.j99.idea.vue.parser.VueParser'
    implements='io.j99.idea.vue.psi.VueCompositeElement'
    extends='io.j99.idea.vue.psi.impl.VueCompositeElementImpl'
    extends("code")='io.j99.idea.vue.psi.impl.VueCompositeHostElementImpl'
    implements("code")="com.intellij.psi.PsiLanguageInjectionHost"
    elementTypeHolderClass='io.j99.idea.vue.VueTypes'
    elementTypeClass='io.j99.idea.vue.psi.VueCompositeElementType'
    tokenTypeClass='io.j99.idea.vue.psi.VueTokenType'
    psiClassPrefix='Vue'
    psiImplClassSuffix='Impl'
    psiPackage='io.j99.idea.vue.psi'
    psiImplPackage='io.j99.idea.vue.psi.impl'
}
private root::=tags
tags    ::='<' tagName ' ' langArr? '>' code '</' tagName '>'
private langArr::= 'lang=' lang
lang::=
code ::=